# Generated by Django 4.0.3 on 2022-04-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.productioncats')),
            ],
        ),
        migrations.AddField(
            model_name='productioncats',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sidebar'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=60)),
                ('contacts', models.CharField(max_length=60)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sidebar')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sidebar')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sidebar')),
            ],
        ),
    ]
