# Generated by Django 4.0.3 on 2022-04-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dko', '0002_client_slug_equipment_slug_equipment_type_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DkoEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('initials', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size_width',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder', models.CharField(max_length=10)),
                ('suffix', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dko.dkoemployer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dko.marketemployer')),
            ],
        ),
    ]
